# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e59882b7fcde7f2435afbddb2f518b0039bd9ee3a54550f134af92902be6b5e61947b4e3e4efc15efdf24a92ec606cefc6516df28ccca0f7702e751c08df50d

test:
  secret_key_base: 1075ef2197b29a6bc83ca151c9434d13a2ad4a4ceb54d75c25a49385d821c6bc2164190743f2d77b3ddeda5d3d329ec6ac8f0c1c4f6f91ef5a2f6ae8c532723f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
